### ISSUE TITLE
Convert @handles to paths instead of using the partial config

### ISSUE THREAD

**Issue by LostKobrakai** [frctl/consolidate#2]
Judging by the test [here](https://github.com/tj/consolidate.js/blob/master/test/shared/partials.js) it seems like only 4 of the many consolidate templating engines do support the partials option. I'm not sure how difficult it would be to just replace the @ handles with the actual paths instead, but it would certainly expand the possibilities of the adapter.

**Comment by tnottu** [comment]
I would like to use Fractal components with WordPress and currently my biggest blocker is the usage of `@` handles.

You can use TWIG templating language in WordPress themes if you install an awesome plugin called Timber (http://upstatement.com/timber/). If I want to write components which are compatible with Fractal and Timber, I would have to write a custom TWIG loader, so that Timber would know how to load the templates by their handles. That shouldn't be too hard either and I started writing one, but unfortunately I'm not very good at php, so I didn't get very far.

Of course there will be other problems and issues ahead, but currently this one is the most problematic.

**Comment by LostKobrakai** [comment]
I've create an adapter, which renders templates in php, but it would need some manual setup and there's not really documentation by now: https://github.com/LostKobrakai/twig

**Comment by allmarkedup** [comment]
@tnottu Yes getting a good twig adapter together is definitely high on my list of priorities at the moment as it would really open up PHP integrations. @LostKobrakai has done some great work with his which uses the native PHP version under the hood and when I'm back from holiday I'll hopefully see if there is anything I can contribute to it.

I think a proper Twig.js adapter (i.e. without calling down to the native PHP version) is also very much needed as an option and so see what I can do.

@LostKobrakai I'm going to close this issue because I'm not sure that there is much else I can do with regards to improving compatability via this consolidate adapter. If you disagree please feel free to re-open!

I've created a separate issue on the main fractal repo to track the feature request for a full-featured twig adapter: https://github.com/frctl/fractal/issues/126
